from typing import BinaryIO


class Blob:
    name: str
    metadata: dict[str, str] | None

    def upload_from_file(self, file_obj: BinaryIO, content_type: str | None = ...) -> None: ...
    def delete(self) -> None: ...
    def patch(self) -> None: ...
    def exists(self) -> bool: ...
    def reload(self) -> None: ...


class Bucket:
    name: str

    def blob(self, blob_name: str) -> Blob: ...


def bucket(name: str | None = ..., app: object | None = ...) -> Bucket: ...
